modLoader="javafml"
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

[[mods]]
modId="matex"
version="1.16.1-v1.5.0"
displayName="Materials Expanded"
#logoFile="examplemod.png" #logo file
authors="Advaluti"
credits=""
description='''Materials Expanded by Advaluti'''