modLoader="javafml"
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

[[mods]]
modId="matex"
version="1.3.2-1.16.1"
displayName="Materials Expanded"
#logoFile="examplemod.png" #logo file
authors="Advaluti"
credits=""
description='''Materials Expanded by Advaluti'''