modLoader="javafml"
loaderVersion="[34,35)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]]
modId="matex"
version="1.16.3-v1.8.1"
displayName="Materials Expanded"
#logoFile="examplemod.png" #logo file
authors="Advaluti"
credits=""
description='''Materials Expanded by michaelsixtyfour'''